"""Enumerations used throughout the application."""


class TripStatus:
    CREATED = "CREATED"
    SCANNED = "SCANNED"
    RECOGNIZING = "RECOGNIZING"
    RECOGNIZED = "RECOGNIZED"
    ANALYZED = "ANALYZED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    FINALIZED = "FINALIZED"
    EXPORTED = "EXPORTED"


class DocumentType:
    PDF = "PDF"
    IMAGE = "IMAGE"
    UNKNOWN = "UNKNOWN"


class OCRStatus:
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class InvoiceType:
    TRAIN_TICKET = "TRAIN_TICKET"
    FLIGHT_TICKET = "FLIGHT_TICKET"
    HOTEL_INVOICE = "HOTEL_INVOICE"
    TAXI_INVOICE = "TAXI_INVOICE"
    RIDE_HAILING_INVOICE = "RIDE_HAILING_INVOICE"
    MEAL_INVOICE = "MEAL_INVOICE"
    VAT_INVOICE = "VAT_INVOICE"
    QUOTA_INVOICE = "QUOTA_INVOICE"
    BUS_TICKET = "BUS_TICKET"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class ExpenseCategory:
    INTERCITY_TRANSPORT = "INTERCITY_TRANSPORT"
    LOCAL_TRANSPORT = "LOCAL_TRANSPORT"
    LODGING = "LODGING"
    MEAL = "MEAL"
    REFUND_CHANGE_FEE = "REFUND_CHANGE_FEE"
    TRAVEL_INSURANCE = "TRAVEL_INSURANCE"
    EXPRESS_LOGISTICS = "EXPRESS_LOGISTICS"
    OFFICE_SUPPLIES = "OFFICE_SUPPLIES"
    ELECTRONICS_DIGITAL = "ELECTRONICS_DIGITAL"
    SOFTWARE_SERVICE = "SOFTWARE_SERVICE"
    COMMUNICATION = "COMMUNICATION"
    GENERAL_SERVICE = "GENERAL_SERVICE"
    DAILY_GENERAL = "DAILY_GENERAL"
    OTHER = "OTHER"


class ReimbursementStatus:
    THIS_TRIP = "THIS_TRIP"
    ALREADY_REIMBURSED = "ALREADY_REIMBURSED"
    NOT_REIMBURSED = "NOT_REIMBURSED"
    PENDING = "PENDING"


class TripReimbursementStatus:
    NOT_REIMBURSED = "NOT_REIMBURSED"
    REIMBURSED = "REIMBURSED"
    PARTIAL_REIMBURSED = "PARTIAL_REIMBURSED"
    NOT_REQUIRED = "NOT_REQUIRED"


class ReviewStatus:
    AUTO_CONFIRMED = "AUTO_CONFIRMED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    MANUALLY_CONFIRMED = "MANUALLY_CONFIRMED"
    REJECTED = "REJECTED"


class TransportType:
    TRAIN = "TRAIN"
    FLIGHT = "FLIGHT"
    BUS = "BUS"
    TAXI = "TAXI"
    RIDE_HAILING = "RIDE_HAILING"
    SUBWAY = "SUBWAY"
    OTHER = "OTHER"


class IssueSeverity:
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


class JobType:
    SCAN = "SCAN"
    RECOGNIZE = "RECOGNIZE"
    ANALYZE = "ANALYZE"
    EXPORT = "EXPORT"


class JobStatus:
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"