#!/usr/bin/env bash
set -Eeuo pipefail

# User-level A100 acceptance tunnel modeled on Paper Wiki:
# browser -> VPS Caddy -> VPS loopback -> SSH reverse tunnel -> A100 loopback.
#
# This mode intentionally uses eager Celery and an in-memory broker so it can
# run without sudo or a system Redis. It is an acceptance fixture, not the
# production worker topology. Production must use setup-a100.sh and the
# independent CPU/GPU systemd units below deploy/a100/systemd/.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
SCRIPT_PATH="$SCRIPT_DIR/$(basename "${BASH_SOURCE[0]}")"
ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/.env.tunnel}"
DEFAULT_DATA_ROOT="${TRIP_HELPER_TUNNEL_ROOT:-$HOME/.local/share/trip-helper}"
DEFAULT_VENV_PATH="${VENV_PATH:-$ROOT_DIR/.venv}"
COMMAND="${1:-help}"

usage() {
  cat <<'USAGE'
Usage: deploy/a100/tunnel.sh <bootstrap|setup|start|stop|restart|status|test|create-admin|create-user>

Runs Trip Helper on the A100 user account and connects it to the VPS through
an SSH reverse tunnel for local acceptance. No Docker, sudo, public A100 port,
or WireGuard is used. Production requires independent workers and Redis.
USAGE
}

random_value() {
  local bytes="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes"
  else
    od -An -N "$bytes" -tx1 /dev/urandom | tr -d ' \n'
  fi
}

write_env_var() {
  printf '%s=%q\n' "$1" "$2"
}

create_environment() {
  local data_root="$DEFAULT_DATA_ROOT"
  local database_url="sqlite:///$data_root/trip-helper.db"

  mkdir -p "$(dirname "$ENV_FILE")" "$data_root"
  chmod 700 "$data_root"
  umask 077
  {
    printf '%s\n' '# Generated by deploy/a100/tunnel.sh. Keep this file private.'
    write_env_var APP_ENV tunnel
    write_env_var TUNNEL_ACCEPTANCE_ONLY true
    write_env_var APP_NAME "Trip Helper"
    write_env_var APP_DOMAIN trip.ninghui.ren
    write_env_var PUBLIC_API_PREFIX /api/v1
    write_env_var LOG_LEVEL INFO
    write_env_var DATABASE_URL "$database_url"
    write_env_var STORAGE_ROOT "$data_root/storage"
    write_env_var SESSION_SECRET "$(random_value 48)"
    write_env_var BOOTSTRAP_TOKEN "$(random_value 32)"
    write_env_var COOKIE_SECURE true
    write_env_var TRUSTED_PROXY_CIDRS 127.0.0.1/32
    write_env_var TASKS_EAGER true
    write_env_var CELERY_TASK_ALWAYS_EAGER true
    write_env_var REDIS_URL memory://
    write_env_var CELERY_BROKER_URL memory://
    write_env_var CELERY_RESULT_BACKEND cache+memory://
    write_env_var OCR_PROVIDER mineru
    write_env_var MINERU_API_URL http://127.0.0.1:8888
    write_env_var MINERU_ENABLED true
    write_env_var MINERU_BACKEND hybrid-engine
    write_env_var MINERU_PARSE_METHOD auto
    write_env_var TESSERACT_FALLBACK_ENABLED true
    write_env_var TESSERACT_COMMAND tesseract
    write_env_var TESSERACT_LANGUAGES chi_sim+eng
    write_env_var REMOTE_OCR_ENABLED false
    write_env_var VPS_TARGET zhijiage
    write_env_var REMOTE_BIND_HOST 127.0.0.1
    write_env_var REMOTE_API_PORT 19829
    write_env_var LOCAL_API_HOST 127.0.0.1
    write_env_var LOCAL_API_PORT 18001
    write_env_var PUBLIC_URL https://trip.ninghui.ren
  } >"$ENV_FILE"
  chmod 600 "$ENV_FILE"
  printf 'Created private tunnel environment at %s\n' "$ENV_FILE"
}

load_environment() {
  if [[ ! -f "$ENV_FILE" ]]; then
    create_environment
  fi

  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a

  VENV_PATH="${VENV_PATH:-$DEFAULT_VENV_PATH}"
  local storage_root="${STORAGE_ROOT:?STORAGE_ROOT is required}"
  if [[ -n "${TUNNEL_RUNTIME_ROOT:-}" ]]; then
    RUNTIME_ROOT="$TUNNEL_RUNTIME_ROOT"
  else
    RUNTIME_ROOT="$(dirname "$storage_root")"
  fi
  PID_DIR="$RUNTIME_ROOT/pids"
  LOG_DIR="$RUNTIME_ROOT/logs"
  LOCAL_API_HOST="${LOCAL_API_HOST:-127.0.0.1}"
  LOCAL_API_PORT="${LOCAL_API_PORT:-18001}"
  REMOTE_BIND_HOST="${REMOTE_BIND_HOST:-127.0.0.1}"
  REMOTE_API_PORT="${REMOTE_API_PORT:-19829}"
  VPS_TARGET="${VPS_TARGET:-zhijiage}"
  PUBLIC_URL="${PUBLIC_URL:-https://${APP_DOMAIN:?APP_DOMAIN is required}}"
  PUBLIC_API_PREFIX="${PUBLIC_API_PREFIX:-/api/v1}"
  PUBLIC_API_PREFIX="/${PUBLIC_API_PREFIX#/}"
  PUBLIC_API_PREFIX="${PUBLIC_API_PREFIX%/}"

  [[ "${APP_ENV:-}" == "tunnel" ]] || {
    printf 'APP_ENV=tunnel is required in %s\n' "$ENV_FILE" >&2
    exit 1
  }
  [[ "${TUNNEL_ACCEPTANCE_ONLY:-}" == "true" ]] || {
    printf 'Tunnel mode is acceptance-only; set TUNNEL_ACCEPTANCE_ONLY=true or use native production services.\n' >&2
    exit 1
  }
  [[ "${SESSION_SECRET:-}" != "" && "${SESSION_SECRET:-}" != "SESSION_SECRET" ]] || {
    printf 'Set SESSION_SECRET in %s\n' "$ENV_FILE" >&2
    exit 1
  }
  [[ "${BOOTSTRAP_TOKEN:-}" != "" && "${BOOTSTRAP_TOKEN:-}" != "BOOTSTRAP_TOKEN" ]] || {
    printf 'Set BOOTSTRAP_TOKEN in %s\n' "$ENV_FILE" >&2
    exit 1
  }
}

ensure_directories() {
  install -d -m 0700 "$RUNTIME_ROOT" "$PID_DIR" "$LOG_DIR" "${STORAGE_ROOT:?}"
}

require_runtime() {
  [[ -x "$VENV_PATH/bin/python" && -x "$VENV_PATH/bin/uvicorn" ]] || {
    printf 'Python runtime missing at %s. Run: %s bootstrap\n' "$VENV_PATH" "$SCRIPT_PATH" >&2
    exit 1
  }
  command -v curl >/dev/null 2>&1 || {
    printf 'curl is required for health checks.\n' >&2
    exit 1
  }
  command -v ssh >/dev/null 2>&1 || {
    printf 'ssh is required for the reverse tunnel.\n' >&2
    exit 1
  }
}

bootstrap_runtime() {
  python3 -m venv "$VENV_PATH"
  "$VENV_PATH/bin/pip" install --upgrade pip wheel
  "$VENV_PATH/bin/pip" install --editable "$ROOT_DIR/backend"
}

local_health() {
  curl -fsS --max-time 5 -H "Host: $APP_DOMAIN" \
    "http://${LOCAL_API_HOST}:${LOCAL_API_PORT}${PUBLIC_API_PREFIX}/health"
}

pid_is_live() {
  local pid_file="$1"
  [[ -f "$pid_file" ]] || return 1
  local pid
  pid="$(<"$pid_file")"
  [[ "$pid" =~ ^[0-9]+$ ]] && kill -0 "$pid" 2>/dev/null
}

start_api() {
  local pid_file="$PID_DIR/api.pid"
  if local_health >/dev/null 2>&1; then
    printf 'A100 API already responds on %s:%s\n' "$LOCAL_API_HOST" "$LOCAL_API_PORT"
    return
  fi
  if pid_is_live "$pid_file"; then
    printf 'A100 API process is alive but unhealthy; inspect %s\n' "$LOG_DIR/api.log" >&2
    return 1
  fi
  rm -f "$pid_file"
  launch_detached _api "$LOG_DIR/api.log"

  for _ in $(seq 1 30); do
    if local_health >/dev/null 2>&1; then
      printf 'A100 API started on %s:%s\n' "$LOCAL_API_HOST" "$LOCAL_API_PORT"
      return
    fi
    sleep 1
  done
  printf 'A100 API did not become healthy; inspect %s\n' "$LOG_DIR/api.log" >&2
  return 1
}

run_api_process() {
  echo "$$" >"$PID_DIR/api.pid"
  exec env "PYTHONPATH=$ROOT_DIR/backend${PYTHONPATH:+:$PYTHONPATH}" \
    "$VENV_PATH/bin/uvicorn" app.main:app \
      --app-dir "$ROOT_DIR/backend" \
      --host "$LOCAL_API_HOST" \
      --port "$LOCAL_API_PORT" \
      --proxy-headers \
      --forwarded-allow-ips=127.0.0.1
}

launch_detached() {
  local action="$1"
  local log_file="$2"
  if command -v setsid >/dev/null 2>&1; then
    setsid -f "$SCRIPT_PATH" "$action" >>"$log_file" 2>&1
  else
    nohup "$SCRIPT_PATH" "$action" >>"$log_file" 2>&1 &
  fi
}

tunnel_watchdog() {
  local ssh_pid=""
  cleanup_watchdog() {
    if [[ -n "$ssh_pid" ]] && kill -0 "$ssh_pid" 2>/dev/null; then
      kill "$ssh_pid" 2>/dev/null || true
      wait "$ssh_pid" 2>/dev/null || true
    fi
    rm -f "$PID_DIR/tunnel.pid"
    exit 0
  }
  trap cleanup_watchdog INT TERM
  echo "$$" >"$PID_DIR/tunnel.pid"

  while true; do
    ssh -N \
      -o ExitOnForwardFailure=yes \
      -o ServerAliveInterval=30 \
      -o ServerAliveCountMax=3 \
      -o TCPKeepAlive=yes \
      -o ConnectTimeout=10 \
      -o StrictHostKeyChecking=accept-new \
      -R "${REMOTE_BIND_HOST}:${REMOTE_API_PORT}:${LOCAL_API_HOST}:${LOCAL_API_PORT}" \
      "$VPS_TARGET" &
    ssh_pid=$!
    wait "$ssh_pid" || true
    ssh_pid=""
    sleep 5
  done
}

start_tunnel() {
  local pid_file="$PID_DIR/tunnel.pid"
  if pid_is_live "$pid_file"; then
    printf 'SSH tunnel watchdog already running.\n'
    return
  fi
  rm -f "$pid_file"
  launch_detached _watch "$LOG_DIR/tunnel.log"
  sleep 1
  if ! pid_is_live "$pid_file"; then
    printf 'Tunnel watchdog exited; inspect %s\n' "$LOG_DIR/tunnel.log" >&2
    return 1
  fi
  printf 'Tunnel watchdog started: VPS %s:%s -> A100 %s:%s\n' \
    "$REMOTE_BIND_HOST" "$REMOTE_API_PORT" "$LOCAL_API_HOST" "$LOCAL_API_PORT"
}

stop_managed_process() {
  local label="$1"
  local pid_file="$2"
  if ! [[ -f "$pid_file" ]]; then
    printf '%s is not managed by this script.\n' "$label"
    return
  fi
  local pid
  pid="$(<"$pid_file")"
  if [[ "$pid" =~ ^[0-9]+$ ]] && kill -0 "$pid" 2>/dev/null; then
    kill "$pid" 2>/dev/null || true
    for _ in $(seq 1 10); do
      kill -0 "$pid" 2>/dev/null || break
      sleep 1
    done
  fi
  rm -f "$pid_file"
  printf '%s stopped.\n' "$label"
}

remote_health() {
  ssh -o BatchMode=yes -o ConnectTimeout=10 "$VPS_TARGET" \
    "curl -fsS --max-time 5 -H 'Host: $APP_DOMAIN' 'http://${REMOTE_BIND_HOST}:${REMOTE_API_PORT}${PUBLIC_API_PREFIX}/health'"
}

public_health() {
  curl -fsS --max-time 10 "${PUBLIC_URL%/}${PUBLIC_API_PREFIX}/health"
}

show_status() {
  printf 'API: '
  local_health || true
  printf '\nTunnel: '
  remote_health || true
  printf '\nPublic: '
  public_health || true
  printf '\n'
  printf 'API process: '
  pid_is_live "$PID_DIR/api.pid" && printf 'running\n' || printf 'stopped\n'
  printf 'Tunnel watchdog: '
  pid_is_live "$PID_DIR/tunnel.pid" && printf 'running\n' || printf 'stopped\n'
}

test_links() {
  local failed=0
  printf 'A100 API: '
  local_health || failed=1
  printf '\nVPS tunnel: '
  remote_health || failed=1
  printf '\nPublic API: '
  public_health || failed=1
  printf '\n'
  return "$failed"
}

case "$COMMAND" in
  help|-h|--help)
    usage
    exit 0
    ;;
esac

load_environment
ensure_directories

case "$COMMAND" in
  bootstrap)
    bootstrap_runtime
    ;;
  setup)
    require_runtime
    curl -fsS --max-time 5 "${MINERU_API_URL:-http://127.0.0.1:8888}/health" >/dev/null \
      && printf 'MinerU loopback health check passed.\n' \
      || printf 'MinerU is not reachable; OCR will use its configured fallback.\n'
    printf 'Tunnel environment ready: %s\n' "$ENV_FILE"
    ;;
  start)
    require_runtime
    start_api
    start_tunnel
    ;;
  stop)
    stop_managed_process "Tunnel watchdog" "$PID_DIR/tunnel.pid"
    stop_managed_process "A100 API" "$PID_DIR/api.pid"
    ;;
  restart)
    stop_managed_process "Tunnel watchdog" "$PID_DIR/tunnel.pid"
    stop_managed_process "A100 API" "$PID_DIR/api.pid"
    require_runtime
    start_api
    start_tunnel
    ;;
  status)
    show_status
    ;;
  test)
    test_links
    ;;
  create-admin)
    require_runtime
    cd "$ROOT_DIR/backend"
    exec env "PYTHONPATH=$ROOT_DIR/backend${PYTHONPATH:+:$PYTHONPATH}" \
      "$VENV_PATH/bin/python" -m app.cli create-admin "${@:2}"
    ;;
  create-user)
    require_runtime
    cd "$ROOT_DIR/backend"
    exec env "PYTHONPATH=$ROOT_DIR/backend${PYTHONPATH:+:$PYTHONPATH}" \
      "$VENV_PATH/bin/python" -m app.cli create-user "${@:2}"
    ;;
  _watch)
    require_runtime
    tunnel_watchdog
    ;;
  _api)
    require_runtime
    run_api_process
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac
